---
- name: install apache2 package
  yum:
    name:
      - httpd
      - httpd-devel
  tags: apache2

- name: clean up conf directory
  file:
    path: "/etc/httpd/conf.d/{{ item }}"
    state: absent
  with_items:
    - welcome.conf
    - autoindex.conf
    - userdir.conf
  tags: apache2

- name: copy apache2 conf
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    mode: 0644
  notify: restart apache2 service
  tags: apache2

- name: copy apache2 default conf
  template:
    src: default.conf.j2
    dest: /etc/httpd/conf.d/default.conf
    mode: 0644
  notify: restart apache2 service
  tags: apache2

- name: start apache2 service
  service:
    name: httpd
    state: started
    enabled: true
  tags: apache2
